name: Test that Jupyter-Book builds
on: [push, pull_request]
jobs:
  build:
    if: github.repository == 'MaxGhenis/vote'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Build  # Build Jupyter Book
        shell: bash -l {0}
        run: |
          pip install jupyter-book
          jb build docs/.
