name: Test that Jupyter-Book builds
on: [push, pull_request]
jobs:
  build:
    if: github.repository == 'MaxGhenis/vote'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      # Install dependencies
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Build # Build Jupyter Book
        shell: bash -l {0}
        run: |
          pip install -U
          jb build docs/.
