name: Build and Deploy Jupyter Book
on:
  push:
    branches:    
      - main
jobs:
  build-and-deploy:
    if: github.repository == 'MaxGhenis/vote'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Install dependencies
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
  
      # Build the book
      - name: Build
        shell: bash -l {0}
        run: |
            pip install -U jupyter-book
            jupyter-book build docs

       # Push the book's HTML to github-pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
