name: Build and Deploy Jupyter Book
on:
  push:
    branches:    
      - main
jobs:
  build-and-deploy:
    if: github.repository == 'MaxGhenis/vote'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      # Install dependencies
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
  
      - name: Build  # Build Jupyter Book
        shell: bash -l {0}
        run: |
            pip install -U "jupyter-book>=0.7.0"
            jb build docs/.

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages  # The branch the action should deploy to.
          FOLDER: docs/_build/html  # The folder the action should deploy.
