name: Build and Deploy Jupyter Book
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    if: github.repository == 'MaxGhenis/vote'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Install dependencies
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      # Build the book
      - name: Build
        shell: bash -l {0}
        run: |
          pip install -U jupyter-book
          jupyter-book build docs

        # Push the book's HTML to github-pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
          cname: vote.maxghenis.com
